### PR TITLE
Improve a few things

### PR DESCRIPTION
**Pull request by art0007i**
- redo csproj to be better.
- change version number to 1.0.0 (because the current github release is 1.0.0 so the version in the mod should be at least that)
- use regex parsing for youtube video id. (I think it's more robust than whatever it was doing before)
- use UriBuilder instead of StringBuilder (fixes at least 1 bug)
- rework mod to import things like in vid attached. it means that it's possible to import the proxy vids as 360 or any other way you want.

https://github.com/user-attachments/assets/e2fdc7c6-eda6-4adc-b50a-cf607fa86445

### CODE REVIEW

**Comment by LeCloutPanda** [comment]
I won't merge this just yet as I want to look at it more in a few hours but may I ask why do you have ``?dummyParam=1``? Also if you can change it to be v1.1.0 that would be lovely.

**Comment by LeCloutPanda** [comment]
Ahh okay also I just noticed I didn't push my latest code to main for v1.0.0 before releasing, that's fine I'll sort it later.

**Comment by art0007i** [comment]
> may I ask why do you have `?dummyParam=1`?

it's basically to not show the "Video Proxy" button twice. because you go into the same root menu, but you have to detect if it's the 2nd time or first time. you can see the code that checks for it in line 64 and code that adds it in line 190

**Comment by LeCloutPanda** [comment]
Opening this back up as on a rare occasion I get errors like this
``Unhandled Exception when updating world: Blue Galaxy - Grid. State Running, Refresh Stage: Connectors, Init State: Finished, SyncTick 12699, StateVersion: 8442212
System.InvalidOperationException: CurrentlyUpdating mismatch.``, could it be the fact stuff is happening too quickly? like do we need a frame or two delay?

**Comment by LeCloutPanda** [comment]
So it seems I just needed a ``__instance.RunInUpdates(3, () => {});``

**Pull request merged**
